//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualFileStorage.PL.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActualFileStorage.PL.Localization.InfoRes", typeof(InfoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string AuthLoginValue {
            get {
                return ResourceManager.GetString("AuthLoginValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string AuthPassword {
            get {
                return ResourceManager.GetString("AuthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о файле.
        /// </summary>
        public static string FileInfoTitle {
            get {
                return ResourceManager.GetString("FileInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя папки.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string RegBDate {
            get {
                return ResourceManager.GetString("RegBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string RegEmail {
            get {
                return ResourceManager.GetString("RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный e-mail.
        /// </summary>
        public static string RegErrorEmail {
            get {
                return ResourceManager.GetString("RegErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректное имя.
        /// </summary>
        public static string RegErrorFirstName {
            get {
                return ResourceManager.GetString("RegErrorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный логин уже занят.
        /// </summary>
        public static string RegErrorLoginOccupied {
            get {
                return ResourceManager.GetString("RegErrorLoginOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректную фамилию.
        /// </summary>
        public static string RegErrorSecondName {
            get {
                return ResourceManager.GetString("RegErrorSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string RegFirstName {
            get {
                return ResourceManager.GetString("RegFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаемый логин.
        /// </summary>
        public static string RegLoginValue {
            get {
                return ResourceManager.GetString("RegLoginValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string RegPassword {
            get {
                return ResourceManager.GetString("RegPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string RegSecondName {
            get {
                return ResourceManager.GetString("RegSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткая ссылка.
        /// </summary>
        public static string ShortLink {
            get {
                return ResourceManager.GetString("ShortLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень доступа.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
